### PR TITLE
fix svg spritesheet syntax and update import function to close tags c…

### LINKED ISSUE #224: svg-icon file + importer function are leaving open tags in HTML
Deryk and I looked into this and discovered there were some issues with the svg spritesheet for theme icons. 

Pushing a fix shortly, this is mostly for tracking purposes.

### PR DESCRIPTION
**Pull request by n-lamkin**
…orrectly.

Fixes #224

### CODE REVIEW

File: functions.php [hunk 1]
```diff
@@ -105,11 +105,18 @@ function braftonium_fonts() {
 function braftonium_get_svg_path($svgid) {
 	// WP_Filesystem();
 	// global $wp_filesystem;
-	$file_data = get_template_directory_uri().'/library/theme-options/svg-icons.svg';
+	/*
```
Comment (dking3876) [inline functions.php]: please leave a todo comment.

syntax is and will get flagged in a code sniffer. 
`/**
  *@todo blah blah blah
 */ `

Comment (n-lamkin) [reply functions.php]: newly added the todo comment
